# Generated by Django 4.2.2 on 2023-07-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
