# Generated by Django 4.2.2 on 2023-07-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0002_buttonstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttonstate',
            options={'verbose_name_plural': 'Button View'},
        ),
    ]
