# Generated by Django 4.2.2 on 2023-07-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0004_alter_studentdetails_current_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='Current_CGPA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Keam',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='S_eight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='S_five',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='S_four',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='S_one',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='S_seven',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='S_six',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='S_three',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='S_two',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
