# Generated by Django 4.2.2 on 2023-07-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('IT', 'Information Technology'), ('CE', 'Civil Engineering'), ('AIDS', 'Artificial Intelligence and Data Science'), ('AEI', 'Applied Electronics & Instrumentation Engineering'), ('None', 'Company')], default='Unknown', max_length=4, null=True),
        ),
    ]
