# Generated by Django 4.2.2 on 2023-06-27 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.CharField(max_length=10)),
                ('data', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'PIE & GRAPH',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('EEE', ' Electrical and Electronic Engineering'), ('IT', 'Information Technology'), ('CE', 'Civil Engineering'), ('AIDS', 'Artificial Intelligence and Data Science'), ('AEI', 'Applied Electronics & Instrumentation Engineering')], default='Unknown', max_length=4, null=True)),
                ('admission_no', models.IntegerField()),
                ('StdEmail', models.EmailField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='staff_app.staff')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
