# Generated by Django 4.2.2 on 2023-07-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_student_import_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='import_type',
        ),
    ]
