# Generated by Django 4.2.2 on 2023-07-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_jobapplication_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='removed_by_company',
            field=models.BooleanField(default=False),
        ),
    ]
