# Generated by Django 4.2.2 on 2023-07-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_jobapplication_removed_by_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='removed_by_company',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
