# Generated by Django 4.2.2 on 2023-07-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_jobapplication_removed_by_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_active',
        ),
    ]
