# Generated by Django 4.2.2 on 2023-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_jobapplication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ROUND2', 'Selected for Round 2'), ('ROUND3', 'Selected for Round 3')], default='None', max_length=20),
        ),
    ]
