# Generated by Django 4.2.2 on 2023-07-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Application Accepted'), ('REJECTED', 'Rejected'), ('ROUND2', 'Selected for 2nd Round'), ('ROUND3', 'Selected for 3rd Round'), ('ROUND_Final', 'Selected for Final Round'), ('PLACED', 'Congrats!You are Placed'), ('Remove', 'You Failed to Clear')], default='None', max_length=20),
        ),
    ]
