# Generated by Django 4.2.2 on 2023-07-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
    ]
